

#server.port=8081 (remove this if necessary) if you are working on multiple projects you cannot run all projects on 8080 at the same time you need to change ports for another project.


server:
  port: 8080

  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never


    #servlet:
    #context-path: /api/v0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_course
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: name
      password: password



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      '[hibernate.format_sql]': true


logging:
  file:
    name: logs/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.tpe]': DEBUG


management: #actuator
  endpoints:
    web:
      exposure:
        include: ['health', 'loggers', 'env', 'beans']

  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always

    shutdown:
      enabled: true